const platformCategories = {
    facebook: [
      "Vehicles", "Property Rentals", "Apparel", "Electronics", "Entertainment",
      "Family", "Free Stuff", "Garden & Outdoor", "Hobbies", "Home Goods",
      "Home Improvement Supplies", "Musical Instruments", "Office Supplies",
      "Pet Supplies", "Sporting Goods", "Toys & Games", "Health & Beauty",
      "Miscellaneous"
    ],
    kijiji: [
      "Buy & Sell", "Cars & Vehicles", "Real Estate", "Jobs", "Services",
      "Pets", "Vacation Rentals", "Community"
    ],
    craigslist: [
        "antiques",
        "appliances",
        "arts & crafts",
        "atvs, utvs, snowmobiles",
        "auto parts",
        "auto wheels & tires",
        "aviation",
        "baby & kid stuff",
        "barter",
        "bicycle parts",
        "bicycles",
        "boat parts",
        "boats",
        "books & magazines",
        "business/commercial",
        "cars & trucks",
        "cds / dvds / vhs",
        "cell phones",
        "clothing & accessories",
        "collectibles",
        "computer parts",
        "computers",
        "electronics",
        "farm & garden",
        "free stuff",
        "furniture",
        "garage & moving sales",
        "general for sale",
        "health and beauty",
        "heavy equipment",
        "household items",
        "jewelry",
        "materials",
        "motorcycle parts",
        "motorcycles/scooters",
        "musical instruments",
        "photo/video",
        "rvs",
        "sporting goods",
        "tickets",
        "tools",
        "toys & games",
        "trailers",
        "video gaming",
        "wanted"
    ],
    ebay: [
      "Antiques", "Art", "Baby", "Books", "Business & Industrial",
      "Cameras & Photo", "Cell Phones & Accessories", "Clothing, Shoes & Accessories",
      "Coins & Paper Money", "Collectibles", "Computers/Tablets & Networking",
      "Consumer Electronics", "Crafts", "Dolls & Bears", "DVDs & Movies",
      "eBay Motors", "Entertainment Memorabilia", "Gift Cards & Coupons",
      "Health & Beauty", "Home & Garden", "Jewelry & Watches", "Music",
      "Musical Instruments & Gear", "Pet Supplies", "Pottery & Glass",
      "Real Estate", "Specialty Services", "Sporting Goods", "Sports Mem, Cards & Fan Shop",
      "Stamps", "Tickets & Experiences", "Toys & Hobbies", "Travel",
      "Video Games & Consoles", "Everything Else"
    ]
  };
  
  module.exports = platformCategories;
  